spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codingbottle
    username: user
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    open-in-view: false