server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/server-session-jpa-restful # ?? ???? ??
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false